import { AuthError } from "@supabase/supabase-js";

const AUTH_ERROR_MESSAGE: Record<string, string> = {
  unexpected_failure: "알 수 없는 오류가 발생했습니다.",
  validation_failed: "이메일 주소가 올바르게 입력되지 않았습니다",
  bad_json: "잘못된 요청 형식입니다.",
  email_exists: "이미 존재하는 이메일입니다.",
  phone_exists: "이미 존재하는 전화번호입니다.",
  bad_jwt: "유효하지 않은 인증 토큰입니다.",
  not_admin: "관리자 권한이 없습니다.",
  no_authorization: "권한이 없습니다.",
  user_not_found: "사용자를 찾을 수 없습니다.",
  session_not_found: "세션을 찾을 수 없습니다.",
  session_expired: "세션이 만료되었습니다.",
  refresh_token_not_found: "리프레시 토큰이 존재하지 않습니다.",
  refresh_token_already_used: "리프레시 토큰이 이미 사용되었습니다.",
  flow_state_not_found: "Flow 상태를 찾을 수 없습니다.",
  flow_state_expired: "Flow 상태가 만료되었습니다.",
  signup_disabled: "회원가입이 비활성화된 상태입니다.",
  user_banned: "해당 사용자는 차단되었습니다.",
  provider_email_needs_verification: "이메일 인증이 필요합니다.",
  invite_not_found: "초대 정보를 찾을 수 없습니다.",
  bad_oauth_state: "OAuth 상태 값이 잘못되었습니다.",
  bad_oauth_callback: "OAuth 콜백 오류가 발생했습니다.",
  oauth_provider_not_supported: "지원하지 않는 OAuth 제공자입니다.",
  unexpected_audience: "잘못된 인증 요청입니다.",
  single_identity_not_deletable: "해당 계정은 삭제할 수 없습니다.",
  email_conflict_identity_not_deletable:
    "이메일 충돌로 인해 삭제할 수 없습니다.",
  identity_already_exists: "이미 존재하는 계정입니다.",
  email_provider_disabled: "이메일 로그인이 비활성화되었습니다.",
  phone_provider_disabled: "전화번호 로그인이 비활성화되었습니다.",
  too_many_enrolled_mfa_factors: "등록된 MFA 요소가 너무 많습니다.",
  mfa_factor_name_conflict: "MFA 이름이 충돌합니다.",
  mfa_factor_not_found: "MFA 요소를 찾을 수 없습니다.",
  mfa_ip_address_mismatch: "MFA IP 주소가 일치하지 않습니다.",
  mfa_challenge_expired: "MFA 인증이 만료되었습니다.",
  mfa_verification_failed: "MFA 인증에 실패했습니다.",
  mfa_verification_rejected: "MFA 인증이 거부되었습니다.",
  insufficient_aal: "인증 수준이 부족합니다.",
  captcha_failed: "캡차 인증에 실패했습니다.",
  saml_provider_disabled: "SAML 제공자가 비활성화되었습니다.",
  manual_linking_disabled: "수동 계정 연결이 비활성화되었습니다.",
  sms_send_failed: "SMS 발송에 실패했습니다.",
  email_not_confirmed: "이메일이 인증되지 않았습니다.",
  phone_not_confirmed: "전화번호가 인증되지 않았습니다.",
  reauth_nonce_missing: "재인증 nonce가 없습니다.",
  saml_relay_state_not_found: "SAML relay 상태가 없습니다.",
  saml_relay_state_expired: "SAML relay 상태가 만료되었습니다.",
  saml_idp_not_found: "SAML IDP를 찾을 수 없습니다.",
  saml_assertion_no_user_id: "SAML Assertion에 사용자 ID가 없습니다.",
  saml_assertion_no_email: "SAML Assertion에 이메일 정보가 없습니다.",
  user_already_exists: "사용자가 이미 존재합니다.",
  sso_provider_not_found: "SSO 제공자를 찾을 수 없습니다.",
  saml_metadata_fetch_failed: "SAML 메타데이터 로딩 실패.",
  saml_idp_already_exists: "SAML IDP가 이미 존재합니다.",
  sso_domain_already_exists: "SSO 도메인이 이미 존재합니다.",
  saml_entity_id_mismatch: "SAML Entity ID 불일치",
  conflict: "이미 존재하거나 충돌했습니다.",
  provider_disabled: "해당 인증 제공자가 비활성화되었습니다.",
  user_sso_managed: "SSO로 관리되는 사용자이므로 수정할 수 없습니다.",
  reauthentication_needed: "다시 인증해야 합니다.",
  same_password: "새 비밀번호가 기존과 동일합니다.",
  reauthentication_not_valid: "재인증 정보가 올바르지 않습니다.",
  otp_expired: "OTP가 만료되었습니다.",
  otp_disabled: "OTP 기능이 비활성화되었습니다.",
  identity_not_found: "계정을 찾을 수 없습니다.",
  weak_password: "비밀번호가 너무 약합니다.",
  over_request_rate_limit: "요청이 너무 많습니다.",
  over_email_send_rate_limit: "이메일 발송 한도를 초과했습니다.",
  over_sms_send_rate_limit: "SMS 발송 한도를 초과했습니다.",
  bad_code_verifier: "코드 검증 실패.",
  anonymous_provider_disabled: "익명 로그인 기능이 비활성화되었습니다.",
  hook_timeout: "Hook 실행 시간이 초과되었습니다.",
  hook_timeout_after_retry: "재시도 후에도 Hook 실행 시간이 초과되었습니다.",
  hook_payload_over_size_limit: "Hook 데이터 크기 제한을 초과했습니다.",
  hook_payload_invalid_content_type:
    "Hook 요청의 Content-Type이 올바르지 않습니다.",
  request_timeout: "요청 시간이 초과되었습니다.",
  mfa_phone_enroll_not_enabled: "MFA 전화번호 등록이 비활성화됨",
  mfa_phone_verify_not_enabled: "MFA 전화번호 인증이 비활성화됨",
  mfa_totp_enroll_not_enabled: "MFA TOTP 등록이 비활성화됨",
  mfa_totp_verify_not_enabled: "MFA TOTP 인증이 비활성화됨",
  mfa_webauthn_enroll_not_enabled: "MFA WebAuthn 등록이 비활성화됨",
  mfa_webauthn_verify_not_enabled: "MFA WebAuthn 인증이 비활성화됨",
  mfa_verified_factor_exists: "이미 검증된 MFA 요소가 존재합니다.",
  invalid_credentials: "이메일 또는 비밀번호가 올바르지 않습니다.",
  email_address_not_authorized: "허용되지 않은 이메일 주소입니다.",
  email_address_invalid: "유효하지 않은 이메일 주소입니다.",
};

export function generateErrorMessage(error: unknown) {
  if (error instanceof AuthError && error.code) {
    return (
      AUTH_ERROR_MESSAGE[error.code] ??
      "알 수 없는 인증 오류가 발생했습니다. 잠시 후 다시 시도해주세요"
    );
  }
  return "문제가 발생했습니다. 잠시 후 다시 시도해주세요";
}
